# Prefix Ctrl+a로 변경
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# 마우스 지원 활성화
set -g mouse on

# 스크롤 버퍼 크기 늘리기
set -g history-limit 100000

# 윈도우를 닫으면 번호를 재정렬
set -g renumber-windows on

# Escape 키 지연 제거
set -sg escape-time 0

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB:clipboard"

# split panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# pane hjkl 로 이동할수 있도록
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Copy 모드에서 vi 스타일 단축키 사용
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind r source-file ~/.tmux.conf \; display "Reloaded!!"

unbind -T copy-mode-vi MouseDragEnd1Pane
unbind -T copy-mode MouseDragEnd1Pane

set -s extended-keys always
set -s extended-keys-format csi-u
set -as terminal-features 'xterm*:extkeys'


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# TPM 초기화 (파일 맨 아래에 위치해야 함)
run '~/.tmux/plugins/tpm/tpm'