[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on = ["g", "F"]
run = "shell --orphan 'open -a Finder %s'"
desc = "Open selected item in Finder"
