
alias cat="bat"
alias vim="nvim"
alias vi="nvim"
alias vimdiff="nvim -d"
alias sudo="sudo "
alias path="echo $PATH | tr \":\" \"\n\" | nl"
alias ls="lsd"
alias l="ls"
alias ll="ls -al"
alias k="kubecolor"
alias kubectl="kubecolor"
alias grep="rg"
alias top="htop"
alias image="viu"
