# starship print-config | bat

format = "$directory$fill${custom.git_provider}$git_branch${custom.git_wip}$all$line_break$jobs$battery$time$status$container$netns$os$shell$character"
# right_format = "${custom.git_provider}$git_branch${custom.git_wip}$all"


[directory]
truncation_length = 0
truncate_to_repo = false

[fill]
symbol = " "

[java]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bold #1664c0"

[kotlin]
symbol = " "
style = "bold"
format = "[$symbol](bold #B125EA)[$version ]($style)"

[gradle]
symbol = " "
format = "[$symbol($version )]($style)"

[nodejs]
symbol = "󰎙 "
format = "[$symbol($version )]($style)"
style = "bold #6CC24A"

[gcloud]
disabled = true

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
style = "bold white"

[git_status]
stashed = ''

[custom.git_provider]
disabled = false
description = "Display symbol for remote Git server"
command = '''
let git_remote = git ls-remote --get-url
  | parse -r '^(?:[a-z]+://)?(?:[^@/]+@)?(?:[^/:@]*\.)?(?P<provider>github|gitlab|bitbucket)(?:\.[^/:]+)*(?::\d+)?[:/].*$'
  | get provider
  | str join
  | str trim

match $git_remote {
  "github" => { print "" }
  "gitlab" => { print $'(ansi "#FC6D26")(ansi reset)' }
  "bitbucket" => { print $'(ansi "#2684FF")(ansi reset)' }
  _ => { print $'(ansi "#f05133")(ansi reset)' }
}
'''
require_repo = true
when = true
shell = ["nu", "-c"]
style = "bold white"
format = "[$output]($style) "


[custom.git_wip]
require_repo = true
shell = ["nu", "-c"]
when = "if (git log -1 --pretty=%s HEAD | str starts-with --ignore-case 'WIP') { exit 0 } else { exit 1 }"
style = "bold yellow"
format = "[WIP ]($style)"
